version: '3.4'

services:
  myonlinestore:
    image: ${DOCKER_REGISTRY-}myonlinestore
    build:
      context: .
      dockerfile: MyOnlineStore/Dockerfile
    depends_on:
      - authdb
      - citiesdb

  authdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  citiesdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
